import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DynamicMouseBackground from "@/components/DynamicMouseBg";
import DynamicTextDiv from "@/components/DynamicTextDiv";
import RippleEffect from "@/components/RipplEffect";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Custom Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Renders the main content with a dynamic mouse background and text
        container. * Contains the children elements passed to the component
        within a DynamicTextDiv.  */}
        <main className="text-center">
          {children}
          <div className="absolute top-0 left-0 w-full h-full">
            <RippleEffect />
          </div>
        </main>
      </body>
    </html>
  );
}
