import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DynamicMouseBackground from "@/components/DynamibMouseBg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Custom Components",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="text-center">
          <DynamicMouseBackground></DynamicMouseBackground>
          {children}
        </main>
      </body>
    </html>
  );
}
